services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuserPostgre
      POSTGRES_DB: finalgo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: backend-app-1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=superuserPostgre
      - DB_NAME=finalgo
      - DB_PORT=5432
      - REDIS_HOST=redis   # Убедитесь, что приложение подключается к контейнеру Redis через его имя
      - REDIS_PORT=6379